### ISSUE TITLE
V2購物車問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#10]
大家好，草民我剛剛在測試購物車的時候發現
當我結帳並填寫完資料以後，無法轉跳到下一個步驟(完成訂購)
但是信箱可以收到訂單的信
![2017-12-11 1 30 26](https://user-images.githubusercontent.com/34327325/33816938-7fdbb726-de77-11e7-9485-5e84d62aa513.png)

![4](https://user-images.githubusercontent.com/34327325/33816911-61d44a54-de77-11e7-8529-873e0f33205c.png)

**Comment by ryuichl** [comment]
一點小蟲
已用最快速度修復
