### ISSUE TITLE
[BUG] 轉盤表單，更新後出不來

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#104]
第一次製作轉盤時沒有先設定表單，發佈後發現抽獎之後無法填寫表單，黑黑一片，於是回頭補製作表單。

但是補製作後再次發布，玩轉盤後表單還是出不來。

![image](https://user-images.githubusercontent.com/34263114/39692780-6a10207e-5214-11e8-822e-e5c17a28ece4.png)

**Comment by ryuichl** [comment]
第三版的麻煩提在這邊
https://github.com/ryuichl/v3-report/issues

感恩
