### ISSUE TITLE
上傳圖片速度慢

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#109]
技嘉汽車反映 
在上傳圖片時跑得很慢
本來以為是網速的問題
但是傳輪播圖（一次傳很多張時）卻又很快
希望可以改善這個問題

**Comment by wilmaftliu** [comment]
20180522 技嘉又再次提出相同的問題
希望可以找時間處理 目前都是業務（我本人）在幫他們上傳圖片 ＱＡＱ

**Comment by ryuichl** [comment]
FIX
