### ISSUE TITLE
【兆豐反映】加入購物車後選數量時的速度問題

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#110]
下單專案：https://ysicdemo1.ryzo.io/p/ysicdemo1/%E9%A6%96%E9%A0%81.html?rand=1529049583872
在按加入購物車後，選數量時非常非常慢，
客戶端甚至慢到無法選數量。

不好意思煩請確認了，謝謝！

**Comment by ai015606220** [comment]
這個問題是因為客戶的商品限購數量設定為10萬個，造成網頁每加一個商品就會多產生10萬個html物件，效能會被嚴重影響

至於另一個問題需要請 @Grace-Tseng 跟客戶要一下這幾個設定值的情況
物流設定:
![1](https://user-images.githubusercontent.com/10190722/41637248-76c62af0-7485-11e8-9a91-19757bd9aa55.png)
購物車框架設定
![2](https://user-images.githubusercontent.com/10190722/41637252-7ead31aa-7485-11e8-8b3b-b1e2649455a4.png)
