### ISSUE TITLE
內嵌網頁第一次貼上時無反應

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#111]
內嵌youtube的影片
第一次貼上時
iframe的那些標籤會被拿掉
同時畫面也不會有反應
要貼上第二次
完整的標籤才會存在
畫面有反應

第一次
![image](https://user-images.githubusercontent.com/34263719/41571961-33a8efec-73a8-11e8-9aca-817045fbf51b.png)

第二次
![image](https://user-images.githubusercontent.com/34263719/41571975-3a361344-73a8-11e8-866e-c8370421da0f.png)

**Comment by ryuichl** [comment]
貼錯位置囉 這裡是2版回報區

**Comment by ryzojudy** [comment]
!!!立刻換 哈哈哈
