### ISSUE TITLE
【問題】EDM影片發送後顯示圖有問題

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/fuco-report#119]
影片寄出後，影片顯示的圖變得很小，不過仍可以點擊後連至原來的影片
![image](https://user-images.githubusercontent.com/36216073/47130934-9766e900-d2ce-11e8-9378-79a79b00c5a2.png)
再麻煩協助確認，謝謝~

**Comment by Kyle30** [comment]
因為用來撐開影片縮圖的"播放鍵"浮水印掉圖( http 404)
https://ryzo.io/images/edm-img/i-play.png
導致這樣的顯示結果

待修正

**Comment by Kyle30** [comment]
修正 views\edm-editor.mustache:2938
"/images/edm-img/i-play.png" -> "https://ryzo.io/images/edm-img/i-play.png"

Done
