### ISSUE TITLE
【建議】序號與購物優惠的連結

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#14]
來自經銷商鼎晉Vincent的建議
目前的序號產生器為O2O的方式，線上取得序號後線下核銷。建議可以將序號取得後可以在購物車裡輸入線上序號，直接做線上結帳前的優惠碼。

**Comment by ryuichl** [comment]
感覺有點迂迴
怎樣做活動才會先有序號
才去購物?

**Comment by wilmaftliu** [comment]
如果先有活動頁 取得序號後，可以直接跳轉到購物頁，或是提供連結，這也是一種方式。
除了使用場景之外，未來WEBA可以做到的互動類型，是否都是O2O，或是因為有了購物車之後要開發純線上的優惠互動，再麻煩產品部思考與整理。
