### ISSUE TITLE
EDM bug ! 

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#18]
【名單群組】
1. 已建立的名單群組要刪除之前已建立的聯絡人點擊刪除顯示【成功】後人還是在上面。
2. 名單新增【名單群組】成功後，但在名單管理頁面沒出現。

【編輯頁面】
文字置中置左置右沒有用

**Comment by Kyle30** [comment]
Re: 
【名單群組】
    1. 目前 Mailchimp( EDM 寄發系統所串接的平台 ) 在寄送 Email 給 "不存在" 的 Email Address 時 , 會將聯絡人的狀態(這項資訊未顯示在 UI 上) , 自動調整為 Cleaned﹒ 這個狀態代表此聯絡人無效 , 所以將無法在對這個聯絡人進行任何操作修改.
    結論 => 之後聯絡人資訊會隱藏其中狀態為 Cleaned 的聯絡人

**Comment by Kyle30** [comment]
Re:
【名單群組】
2. 偶發的 Bug , 測試很多次沒辦法產生同樣的狀況 , 只能等下次出現的時候再來修

**Comment by Isabella-Zheng** [comment]
Dear All:
【編輯頁面 - 文字元件】
**下列bug已修正**：
1.文字 - 對齊(左、中、右)
2.文字 - 項目符號編輯跑板
3.文字 - 複製後無法編輯被複製出來的文字元件

**Comment by ryuichl** [comment]
先close了 有遇到再提出
