### ISSUE TITLE
購物車金流 冬至快問快答

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#19]
各位好，我是一個剛開始學習的小賣家，
在設定Ryzoweba的購物車時，發現一個小問題
就是我目前只想使用ATM匯款的方式進行收款
可是系統很堅持要我輸入完綠界金流的資料才肯放行

救命啊，我真的沒有要使用綠界啊

<img width="1440" alt="2017-12-20 11 20 21" src="https://user-images.githubusercontent.com/34327325/34190207-71f38418-e57a-11e7-97d5-31a7622af84b.png">
-----
以上轉貼自網路小賣家的心情語錄

**Comment by ryuichl** [comment]
隨便填
