### ISSUE TITLE
【建議】分頁網址命名為英文，但選單裡的分頁名稱可以是中文

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#2]
目前URL和頁面名稱是連動的。

由於URL使用中文，會增加搜尋上的困擾，所以客戶會想把分頁網址改成英文的。但一改頁面名稱以後，連選單裡面的頁面名稱就都會是英文，例如Trollbeads的專案: https://trollbeads.ryzo.io/。

建議網址命名與選單中的網頁名稱可以分開設定。

**Comment by ryuichl** [comment]
judy說你沒有問題了

**Comment by ryuichl** [comment]
目前討論結果是之後仍然是連動的
如果你堅持的話可以提出更多觀點

**Comment by Grace-Tseng** [comment]
Just for your information~~ 
只是留個紀錄，如果以後有別的客戶再提，會再補充進來，提供產品優化參考。
