### ISSUE TITLE
表單bug！

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#20]
https://ryzo20170118.ryzo.io/

表單用手機Line＆Safari填完資料後點擊送出，但送出都沒有反應！

**Comment by Kyle30** [comment]
單選方格: 
每一列等於一個"單選"項目 , 若勾選 "必填" 選項則等於每列至少要選一個答案。

複選題請改用核取方塊 , 這不是 Bug 噢 !!
