### ISSUE TITLE
裁切圖片問題

### ISSUE THREAD

**Issue by rexryzo** [ryuichl/fuco-report#22]
元件>圖片>
原本圖片我設定裁切範圍，上傳之後會跑掉
設定的裁切範圍
![default](https://user-images.githubusercontent.com/34876338/34370156-b4cb8092-eafc-11e7-8940-dd6190b4dfa8.PNG)

裁切上傳後
![default](https://user-images.githubusercontent.com/34876338/34370172-c6511336-eafc-11e7-991a-e540f828ca71.PNG)

需要重開機才會恢復正常

**Comment by ryuichl** [comment]
你裁切的時候
瀏覽器縮放比例有調整過嗎?

**Comment by rexryzo** [comment]
有調整過，但狀況沒有改善，直到重開機後才恢復正常!

**Comment by ryuichl** [comment]
現在還有這個狀況嗎?

**Comment by rexryzo** [comment]
我重開機後現在沒有了，但wilma還是建議我提出給工程部

**Comment by ryuichl** [comment]
還有出現一樣狀況再提出來
我們再去幫你看是甚麼問題

**Comment by rexryzo** [comment]
好的，謝謝
