### ISSUE TITLE
【問題】框架選單問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#23]
hi
以下專案網址使用柵欄式選單，
選擇到“環境介紹”以後，選單就會出現排列、或是感應機制的問題
再麻煩檢查

https://student.ryzo.io/

**Comment by Gabe-Liu** [comment]
可以給此專案的帳號密碼嗎??? 
我登進去看一下內容！

**Comment by weilyn** [comment]
你可以聯繫業務rex索取
