### ISSUE TITLE
客戶意見

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#3]
客戶阿治表示：
目前我們在訂單管理系統上並沒有設定~首次購買加入"會員"設定，可以加入這功能?未來可以給會員一些優惠活動。謝謝你。

**Comment by ryuichl** [comment]
目前應該還沒想那麼遠
等第三版購物車規格出來
可以再看是否不足

**Comment by weilyn** [comment]
OK 沒問題
