### ISSUE TITLE
【建議】背景圖在PC上延伸

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#31]
背景可以自己放圖和設定顏色，案例如下：
https://tw-img.vpon.com/img/campaigns/201712_MegRhythm/index.html
https://tw-img.vpon.com/img/campaigns/201712_MegRhythm/form.html
https://tw-img.vpon.com/img/campaigns/201710_MegRhythm/

**Comment by ryuichl** [comment]
三版考慮列入
