### ISSUE TITLE
【建議】資料綁定！資料綁定！資料綁定！（敲碗）

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#34]
這次再度舉辦手機廣告收集比賽，大家都一直來問說自己收集幾筆了。
希望可以趕快有資料綁定，綁定表單回覆資料的筆數，即時更新排行榜～～
才不用人力一直進去更新（累死）。

**Comment by ryuichl** [comment]
反正也沒獎品 
知道有幾筆也沒用

**Comment by Grace-Tseng** [comment]
行銷活動都有機會用到，不限於這次公司內部自己舉辦的活動，
只是提供一個general會用到的情境。
 
FYR

**Comment by ryuichl** [comment]
排程內
靜候佳音
