### ISSUE TITLE
weba 錯誤回報

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#4]
FACEBOOK功能出現異常
發生在分享、及粉絲專頁的選項
![2017-12-07 12 30 54](https://user-images.githubusercontent.com/34327325/33699903-f5e568ce-db50-11e7-806c-aaeed0be4ec8.png)
![2017-12-07 12 31 05](https://user-images.githubusercontent.com/34327325/33699904-f6105520-db50-11e7-9e56-c7a9b183a18e.png)

**Comment by ryuichl** [comment]
確認是BUG
處理中

**Comment by ryuichl** [comment]
已修正
沒問題的話一陣子後會把這個 ISSUE CLOSE
