### ISSUE TITLE
【bug】收縮區塊問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#40]
hi，剛剛有民眾來電表示
收縮區塊顯示有問題
經過專家嚴密測試後發現
當開啟右側的圖示後，在編輯模式便會出現跑版的情況
初次之外，直接點擊編輯區域裏的該元件，無法收闔、展開，但是箭頭會轉方向

![2018-01-12 2 45 29](https://user-images.githubusercontent.com/34327325/34862911-bce7c6fc-f7a7-11e7-9cf1-45c82b6d0890.png)

**Comment by ai015606220** [comment]
跑版問題已修復推上 branch: roy_shopcom_0104 ，箭頭轉向問題因現有寫法牽扯到非常多元件，會等Gabe回來並請教完細節後再改寫
