### ISSUE TITLE
【跑版】分享按鈕

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#42]
框架上的分享按鈕，原本設定為橫的。
但是發布後變成直的，在手機上和電腦上看都是。

示意圖：https://advicenbugs.ryzo.io/Advice1.html
跑版的網頁：https://demo-luckydraw.ryzo.io/首頁.html

**Comment by ai015606220** [comment]
這個問題是因為手機和電腦間有些尺寸單位上的小誤差，造成按鈕在手機上會稍微寬一點，只要將社群分享的元件寬度稍微拉寬一點就沒事了

**Comment by Grace-Tseng** [comment]
收到，建議未來操作介面上可以附上說明～～
