### ISSUE TITLE
【BUG】表單複製功能

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#45]
在選擇「將表單複製給」的帳號選擇處
scroll bar不見了~
在麻煩工程大大們幫忙解決了
感謝!!!
PS.是在carol的帳號中

**Comment by ryzojudy** [comment]
![p_20180126_105439](https://user-images.githubusercontent.com/34263719/35431061-f7edf758-02b5-11e8-8412-39fdc35f8b4e.jpg)

**Comment by ai015606220** [comment]
等待上線
分支: derek_fix_0130
