### ISSUE TITLE
手機預覽功能問題

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#46]
Hi
又是手機預覽問題

我在專案裏將表單的按鈕顏色更改為白色至透明
在預覽、編輯、發布狀態都能夠呈現白色的狀態

但是使用手機預覽功能時就沒有辦法將按鈕隱藏起來
雖然這個需求不常用到，不過可能表示兩邊的顯示沒有同步

![2018-01-26 12 29 36](https://user-images.githubusercontent.com/34327325/35425262-9793ca8e-0294-11e8-8eb2-8cdb60064460.png)

![2018-01-26 12 29 19](https://user-images.githubusercontent.com/34327325/35425265-9ae4c760-0294-11e8-9646-5be08b1c5c1e.png)
送出按鈕無法隱藏起來

再麻煩幫忙查看
草民 敬上

**Comment by Gabe-Liu** [comment]
分支 gabe_debug_0207 done
