### ISSUE TITLE
試用帳號開通時提供的認證信內文修改

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#48]
目前的試用帳號開通後為英文，接下來將開放試用，需要將開通後的內文中文化，並提供帳密以及客服聯繫資訊與教學連結，請協助開放修改，感恩～

**Comment by ryuichl** [comment]
不能開放修改 你把你的版本給我
我再幫你改

**Comment by wilmaftliu** [comment]
好的感恩～
