### ISSUE TITLE
Ryzoweba建議

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#5]
早安，目前粉絲頁已經更新，希望weba裡FB工具預設的網址可以修改為新的粉絲頁網址。
網址如下https://www.facebook.com/ryzoweba
![2017-12-08 10 23 32](https://user-images.githubusercontent.com/34327325/33748234-4fe7eee4-dc02-11e7-92d0-38b3f9a4375b.png)

**Comment by ryuichl** [comment]
這昨天有用過
清快取試試

**Comment by weilyn** [comment]
收到！ 確認OK了 跪謝
