### ISSUE TITLE
[問題 ] weba專案裡按鈕連結

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#51]
你好，以前在專案裡設定連結的時候，只要把網址部分設定為##就可以讓按鈕預設為不動作。
不過最近發現不行了，現在如果在連結地方設定為##，會轉跳到全螢幕撐開的專案狀態

有點難說明，想知道就來問我吧

**Comment by ai015606220** [comment]
等待上線
分支: derek_fix_0130

**Comment by ai015606220** [comment]
已修正，如果想要讓按鈕沒動作，只要網址欄是空白就可以
