### ISSUE TITLE
購物車跑版(OS/iOS)

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#52]
使用Apple OS/iOS系統（電腦或手機都是）進入RyzoWEBA的購物車時，會有跑版情形，手機和電腦的瀏覽器（safari&Chrome)都是相同情況。（數量和金額會超出商品項目的框）細節請見附圖。

<img width="1215" alt="2018-01-30 4 07 54" src="https://user-images.githubusercontent.com/34560641/35604308-a28ea5a8-067c-11e8-91e6-eefc8a7b7def.png">
<img width="1280" alt="2018-01-30 4 07 11" src="https://user-images.githubusercontent.com/34560641/35604309-a2bb0e18-067c-11e8-8654-fe26d2652a6b.png">
![s__46809113](https://user-images.githubusercontent.com/34560641/35604352-de51bc1a-067c-11e8-9114-e1bb45cdff0c.jpg)
![s__46809112](https://user-images.githubusercontent.com/34560641/35604353-deb09faa-067c-11e8-8923-8fd00f6853ff.jpg)

**Comment by ai015606220** [comment]
等待上線
分支: derek_fix_0130
