### ISSUE TITLE
專案下載無法打開壓縮檔

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#54]
![image](https://user-images.githubusercontent.com/34560641/35794247-fde01df8-0a8f-11e8-83f5-6cd0ceef341d.png)
專案下載後無法打開壓縮檔，如題，附圖。
（圖片來源：客戶「高星公關」提供）
小女子親自測試後發現mac版下載後的壓縮檔解壓縮後會創造一個新的「cpgz」檔。
<img width="381" alt="2018-02-05 4 20 20" src="https://user-images.githubusercontent.com/34560641/35794408-8fd81ee0-0a90-11e8-8adf-6028689a673a.png">
感謝大大

**Comment by ryuichl** [comment]
已解
