### ISSUE TITLE
管理員帳號後台-帳號設定

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#55]
選擇帳號時間的地方
跳出來的日曆 一切功能正常
但介面模糊 就像把眼竟拿下來看東西的感覺一樣
在麻煩各位大人們有時間的時候看一下囉~

**Comment by ryzojudy** [comment]
<img width="716" alt="1" src="https://user-images.githubusercontent.com/34263719/35893299-4cd7fd1e-0be8-11e8-858e-a02bc8eb1efc.PNG">

**Comment by Gabe-Liu** [comment]
分支 gabe_debug_0207 done
