### ISSUE TITLE
業務權限-企業清單可以修改

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/fuco-report#57]
業務權限目前可以到企業清單中自行修改裡面的資訊，
麻煩大家處理~

**Comment by wendykuo** [comment]
<img width="1112" alt="2018-02-07 10 38 52" src="https://user-images.githubusercontent.com/36216073/35896036-36f72a1c-0bf5-11e8-8ef0-b2d6a2f02e38.png">
<img width="1268" alt="2018-02-07 10 41 16" src="https://user-images.githubusercontent.com/36216073/35896037-3724f9e2-0bf5-11e8-90f1-6bcf163d7177.png">

**Comment by Gabe-Liu** [comment]
分支 gabe_debug_0207 done
