### ISSUE TITLE
購物車商品庫folder ID對不到（美安測試用急件）

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#58]
複製過來有購物車的專案
但是在新的專案裡 重新新增商品庫 並新增5件商品後
回到編輯頁面時 無法把「加入購物車」的商品串進去

根據凱皇判斷 是因為folder ID對不到 如圖
<img width="1277" alt="2018-02-07 11 09 36" src="https://user-images.githubusercontent.com/34560641/35896576-d7e81c18-0bf7-11e8-8c62-a52c2f80b241.png">
<img width="1276" alt="2018-02-07 11 10 06" src="https://user-images.githubusercontent.com/34560641/35896580-da4645e8-0bf7-11e8-9971-144021ddf6bd.png">

**Comment by ai015606220** [comment]
這個問題是由於從不同帳號複製專案，緊急的解決方法: 可以用新的加入購物車按鈕取代舊的按鈕

**Comment by ryuichl** [comment]
目前不會修正這問題
有購物車的專案要複製的話
先用上面的解法
有新提問可再回覆
