### ISSUE TITLE
【BUG】複製專案掉圖

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#60]
複製的專案圖片沒有一起被複製過去 如題
from 可愛的yaki珠寶阿治
![35149](https://user-images.githubusercontent.com/34560641/35962672-3314692a-0ced-11e8-959b-7fa9d6d774b6.jpg)
![35155](https://user-images.githubusercontent.com/34560641/35962673-35434356-0ced-11e8-9b1f-439c8abc6064.jpg)

**Comment by Kyle30** [comment]
修正內容:
新增 - Site & EDM 在使用複製功能時, 連帶複製 Google Storage Files 的相關邏輯

使用分支:
kyle_bugFix#60

已在本機測試 OK ,等待上線 ...

**Comment by Kyle30** [comment]
已修正
