### ISSUE TITLE
【疑問】帳號資料

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#61]
昨天carol註冊了一個facebook@gmail.com的帳號
但無法在管理元後台新增此帳號
且無法直用登入
但再次用一樣的帳號註冊時
顯示此帳號已存在
不知道發生了甚麼事

**Comment by ryuichl** [comment]
後台看到是有帳號
猜測為密碼打錯

**Comment by ryzojudy** [comment]
剛剛去確認了 他當時註冊的是Facebook@gmail.com
但是在後台只找得到facebook@gmail.com的帳號
在登入頁時：
facebook的帳號顯示尚未驗證
Facebook的帳號顯示無此帳號
重新註冊時：
兩個帳號都顯示此信箱已使用過

**Comment by ryzojudy** [comment]
Facebook@gmail.com登入頁顯示

![image](https://user-images.githubusercontent.com/34263719/36008796-f445bfa4-0d83-11e8-9869-0b19d2ed4d5b.png)

**Comment by ryzojudy** [comment]
facebook@gmail.com的登入頁顯示

![image 1](https://user-images.githubusercontent.com/34263719/36008819-0a725a62-0d84-11e8-8dc6-34bf64864096.png)

**Comment by ryzojudy** [comment]
在總管後台時 找不到Facebook@gmail.com的帳號

![image 2](https://user-images.githubusercontent.com/34263719/36008830-1c75c1cc-0d84-11e8-8f3a-6a5fa73eed75.png)

**Comment by ryzojudy** [comment]
總管後台找得到facebook@gmail.com的帳號

![default](https://user-images.githubusercontent.com/34263719/36008861-4d8e7c68-0d84-11e8-9f52-9e7ee2171833.png)

**Comment by ryuichl** [comment]
上次更新已經改成註冊時
帳號統一全部小寫

**Comment by ryzojudy** [comment]
好的 了解
