### ISSUE TITLE
【BUG】專案匯出掉圖

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#62]
網頁封包可以正常下載，裡面也都有東西了沒錯，
但是圖片都沒有跟著一起下載下來，
正常要有圖片的地方都不會顯示出來。

看了一下封包內的upload資料夾
似乎是因為圖片們沒有跟著一起下載下來

以上是來自客戶高星公關的林之提供 感謝大大

**Comment by Kyle30** [comment]
修正內容:
1.修正 backend.js 專案匯出的圖片相對路徑
2.補回 server_setup 內 "output_dir_css_js" 誤刪的 "mobile-style.css" 項目
使用分支:
kyle_bugFix#62

已在本機測試 OK ,等待上線 ...

**Comment by Kyle30** [comment]
已修正
