### ISSUE TITLE
【BUG】FB 分享圖出不來！！！！！

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#63]
<img width="1260" alt="2018-02-14 10 14 01" src="https://user-images.githubusercontent.com/34700112/36184699-430bb4a0-1170-11e8-97dc-5f0ad55acd15.png">
<img width="1437" alt="2018-02-14 10 13 35" src="https://user-images.githubusercontent.com/34700112/36184700-4336c7f8-1170-11e8-9bd1-7530ec48152b.png">

詳細可以再問kyle解釋一下～～

**Comment by brendatseng** [comment]
![fb-01](https://user-images.githubusercontent.com/34700112/36184723-6934a916-1170-11e8-90f3-9107b4b19b76.png)
要分享這張圖，檔名跟圖檔有關係嗎？？

**Comment by Kyle30** [comment]
Derek 已經改好了, 等待上線中

內容:
修正 publish_template.mustache 中 og:image 的 url 對應

使用分支:
derek_fix_0213

**Comment by Kyle30** [comment]
已修正
