### ISSUE TITLE
(急)試用帳號顯示已達人數上限

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/fuco-report#64]
帳號名稱：nt80825@cathaybk.com.tw
登入沒問題，開始編輯時發生錯誤
錯誤提示顯示內容為：已達人數上限，欲編輯專案請與專人聯絡
放置於fucoryzo+trial@gmail.com之下

**Comment by ryuichl** [comment]
請給更多敘述

**Comment by wendykuo** [comment]
<img width="843" alt="1" src="https://user-images.githubusercontent.com/36216073/36460221-679ea458-16f2-11e8-96a3-b41e8bac6216.PNG">

**Comment by wendykuo** [comment]
<img width="513" alt="default" src="https://user-images.githubusercontent.com/36216073/36460226-6d305966-16f2-11e8-9c6c-12ca65b3d3cc.PNG">

**Comment by ryuichl** [comment]
問題點是?

**Comment by ryzojudy** [comment]
進去檢查過 他的帳號內還沒有專案 但無法編輯使用

**Comment by ryuichl** [comment]
給我一個詳細流程 
字打多一點
這樣我看不懂

**Comment by ryzojudy** [comment]
他的階層是在一般的客戶 應該不會有人數上線的問題(不是放在企業內的)

**Comment by ryuichl** [comment]
錯誤訊息截圖?

**Comment by ryzojudy** [comment]
客戶的流程：
可正常登入
但點擊新增專案時就會跳出那個提示框

**Comment by ryzojudy** [comment]
好 我跟他問問看帳密

**Comment by ryzojudy** [comment]
剛剛跟他了解了 應該是因為第一次就直接用google登入的問題
用手動輸入帳密的話是沒有問題的
