### ISSUE TITLE
【BUG】大轉盤顯示未到活動時間或已超過活動時間

### ISSUE THREAD

**Issue by wendykuo** [ryuichl/fuco-report#68]
今日典藏反映大轉盤設定發佈後，在測試時會出現未到活動時間或已超過活動時間的提示
活動今天就要上架，麻煩大家處理~

**Comment by wendykuo** [comment]
![0be664f0-1330-4301-99a7-5d7807d3b93a](https://user-images.githubusercontent.com/36216073/36586165-a0e7d25a-18bb-11e8-8e6f-04afc002a7fd.jpg)

**Comment by ryuichl** [comment]
已修正
