### ISSUE TITLE
【BUG】表單管理顯示為空白

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#72]
WEBA編輯頁中 表單管理點擊後第一次會出現空白 重新整理後才會出現表單

**Comment by ryuichl** [comment]
圖?

**Comment by wilmaftliu** [comment]
<img width="980" alt="2018-02-26 11 03 12" src="https://user-images.githubusercontent.com/34560641/36651614-b06be920-1ae4-11e8-8b0b-63ed5101b5b1.png">

**Comment by ai015606220** [comment]
修正等待上線中
