### ISSUE TITLE
【BUG】 WEBA的專案管理dashboard裡的預覽功能失效，會出現404頁面

### ISSUE THREAD

**Issue by weilyn** [ryuichl/fuco-report#74]
![2018-02-27 1 17 25](https://user-images.githubusercontent.com/34327325/36711869-c40fc0f0-1bc0-11e8-8ab8-07467e299bc2.png)
![2018-02-27 1 19 02](https://user-images.githubusercontent.com/34327325/36711886-cfcb4c48-1bc0-11e8-9576-321567ce74cc.png)

如題點擊預覽，會出現404
帳號裡隨即抽樣了5個專案都出現此問題
在fucoryzo@gmail.com的帳號裡

**Comment by ryuichl** [comment]
已修正
看不到的專案重新發佈後可正常預覽
