### ISSUE TITLE
【BUG】表單回覆系統信 重複發送

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#76]
如題
帳號為業務帳號 gossipsmb@fucotech.com.tw
3/3 10:11分連續發了四封相同的通知信給三位接受通知的email
請協助了解原因 感謝
<img width="1058" alt="2018-03-05 10 21 09" src="https://user-images.githubusercontent.com/34560641/36954742-f1a3f9bc-205e-11e8-8949-739fd8815c92.png">
<img width="1061" alt="2018-03-05 10 21 00" src="https://user-images.githubusercontent.com/34560641/36954743-f3dc7da8-205e-11e8-9623-31c5646a1b94.png">

**Comment by Kyle30** [comment]
原因:
客戶重複送出表單資料(同時送出四筆), 且再收到一筆就會寄發通知, 於是剛好四筆皆滿足觸發寄信的條件.

待修正
