### ISSUE TITLE
選單裡設定超連結頁面時電腦無法開啟

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#78]
<img width="583" alt="2018-03-07 11 53 44" src="https://user-images.githubusercontent.com/34560641/37073580-c308f8be-2202-11e8-95d2-052d9203e8dc.png">
如題
在頁面選單裡新增「超連結」頁面時，
預覽沒問題，但發布後電腦即使點擊超連結頁面也無法顯示（但手機看正常）

如果在超連結的頁面裡設定勾起「開新分頁」就沒有這個問題。
附上截圖
<img width="392" alt="2018-03-07 12 27 19" src="https://user-images.githubusercontent.com/34560641/37073639-17b728cc-2203-11e8-9134-fa6442994dee.png">

請各位大大有空時協助排解 客戶這邊我們會先建議他們以開新分頁的方式處理
以上 感恩

午餐愉快

**Comment by Gabe-Liu** [comment]
done
