### ISSUE TITLE
小積木-社群 之 圖文不符

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#79]
小積木中的右側還有微博圖示

但是事實上只有台灣幾個社群
希望可以圖文一致
感恩

<img width="809" alt="2018-03-07 12 30 11" src="https://user-images.githubusercontent.com/34560641/37073698-7c8b960c-2203-11e8-9431-53006582be9c.png">

**Comment by wilmaftliu** [comment]
小積木裡上半部圖示是正確的 下半部是微博 微信 ＱＱ等 這些是大陸的圖示 請協助修正成 FB LINE Google+ Twitter Pinterest

**Comment by Gabe-Liu** [comment]
done
