### ISSUE TITLE
【建議】記名ID (RT委員提供)

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#8]
「收集瀏覽者的行為並記名，
確切知道特定會員有無開啟、點擊，以及瀏覽路徑，
如此，做Campaign才有意義。」

**Comment by ryuichl** [comment]
這個我暫時還想不到我們收集這些數據後的下一步要幹嘛
你有想法嗎?

**Comment by Grace-Tseng** [comment]
1. 看瀏覽者是否有照設計者預先設定的路徑走，以優化網頁排版和網頁內容 (沒有點擊應該要點擊的按鈕、跳著看某些頁面並沒有照順序之類)
2. 看瀏覽者最有興趣的區塊、商品、內容是什麼
3. 可以找出活動成效好或不好的原因 (瀏覽者看到哪裡就沒有再往下看、點擊到哪頁以後就跳出了、看完商品後是否有放入購物車等等)

以上是我預想可能會需要的原因

**Comment by ryuichl** [comment]
你這些我看起來都不需要記名耶

**Comment by Grace-Tseng** [comment]
收集會員偏好，未來推送個人化產品資訊
