### ISSUE TITLE
購物車無法下單

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#80]
<img width="517" alt="2018-03-12 9 39 00" src="https://user-images.githubusercontent.com/34560641/37261708-83fcac94-25d9-11e8-88e9-0c69bb6e2561.png">
<img width="493" alt="2018-03-12 9 40 50" src="https://user-images.githubusercontent.com/34560641/37261709-85c688ba-25d9-11e8-8161-a49e476406f3.png">
 
由客戶Yaki珠寶通知
目前使用WEBA將商品放入購物車後，輸入完基本資料後無法下單，請協助了解，感謝！

（我自己測試也無法，不論是銀行匯款或是信用卡刷卡）

**Comment by ryuichl** [comment]
給一個測試的網址吧?

**Comment by wilmaftliu** [comment]
yaki-true-heart.ryzo.io

**Comment by ryuichl** [comment]
受美安功能影響的一點小蟲
已修正
