### ISSUE TITLE
【BUG】專案預覽圖和實際專案內容不同

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#82]
在dashboard的專案預覽圖和實際內容不相符~
這個專案是在今天早上(3/13)時製作的~

**Comment by ryzojudy** [comment]
這是專案預覽處的
![default](https://user-images.githubusercontent.com/34263719/37325762-350ed0ca-26ca-11e8-9c54-b09b38d4d9eb.png)

**Comment by ryzojudy** [comment]
這是實際內容
![default](https://user-images.githubusercontent.com/34263719/37325770-41ffb51a-26ca-11e8-9dcf-5881a6539a63.png)

**Comment by ryuichl** [comment]
ㄜ 他本來就是這樣
恩

**Comment by ryzojudy** [comment]
哈 好喔
