### ISSUE TITLE
GIF播放一次後重load不會重複播放

### ISSUE THREAD

**Issue by wilmaftliu** [ryuichl/fuco-report#83]
客戶禾陽整合行銷代製作的手機官網專案
網址： https://hyimc.ryzo.io

目前首頁的兩層GIF(表層四個小線稿插圖動畫＋裡層輪播照片）
其中表層動畫設定為播放一次，原本應該去到其他頁面再返回or重新整理後，要再播放一次線稿插圖小動畫，但是iphone6s用safari瀏覽時，第二次再進去首頁，動畫就停止播放了，請協助了解原因，感恩～

**Comment by Gabe-Liu** [comment]
done
