### ISSUE TITLE
【BUG】客戶國泰世華-發佈已達上限後專案回到預設狀態

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#84]
與之前正美的狀況有點像
發佈數已達上限 依然點了專案發佈
關閉跳出的提示窗後
回去查看專案
就變回了預設的狀況(專案剛建立的時候)
還在跟他確認專案的建立時間中

國泰的試用帳號：judy-huang@cathaybk.com.tw

**Comment by ryzojudy** [comment]
剛剛收到回覆 是當天創建的
之後若有再測試到相同的情況 會再跟我們連絡

**Comment by ryuichl** [comment]
跟時間沒關係
我後台看他專案是正常的
我覺得是瀏覽器的關係

**Comment by ryzojudy** [comment]
那需要在跟正美也確認一下他們使用的瀏覽器是甚麼嗎?

**Comment by ryuichl** [comment]
我有請grace問
不知道他問了沒

**Comment by ryuichl** [comment]
可以阿

**Comment by ryzojudy** [comment]
好喔 我也在問問看grace跟正美的人

**Comment by ryuichl** [comment]
先關掉了
有一樣問題再提出
