### ISSUE TITLE
吸取顏色時圖片都消失

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#86]
<img width="1332" alt="2018-04-03 15 23 49" src="https://user-images.githubusercontent.com/34700112/38235329-532085a6-3753-11e8-83c1-dcd363401d28.png">

如圖所示,吸取顏色時圖片都消失,無法吸取要的顏色！

**Comment by ryuichl** [comment]
目前確實已經無法吸圖片的顏色
暫不會修正他
