### ISSUE TITLE
分享按鈕有問題

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#87]
分享按鈕的連結一直抓到之前的

https://event05.ryzo.io/p/event05/%E6%89%8B%E6%A9%9F%E8%A1%8C%E9%8A%B7%E8%B6%A8%E5%8B%A2%E8%AC%9B%E5%BA%A7.html?rand=1523241016159

分享按鈕連到fb的分享一直404
<img width="383" alt="2018-04-09 10 38 18" src="https://user-images.githubusercontent.com/34700112/38476863-8be1e25c-3be2-11e8-9fd0-e08923a332c7.png">

**Comment by weilyn** [comment]
![2018-04-09 10 44 40](https://user-images.githubusercontent.com/34327325/38476984-0f2e7ed6-3be3-11e8-888a-606766b68ff1.png)

**Comment by brendatseng** [comment]
<img width="1103" alt="2018-04-09 10 46 36" src="https://user-images.githubusercontent.com/34700112/38477061-60105f22-3be3-11e8-8b61-acbcf19b0861.png">


有時候可以抓到是對的有時候又跑到之前的連結404

**Comment by Kyle30** [comment]
請將網址後面的 " ?rand=XXXXXXXXXXXXX" 移掉.

如
https://event05.ryzo.io/p/event05/%E6%89%8B%E6%A9%9F%E8%A1%8C%E9%8A%B7%E8%B6%A8%E5%8B%A2%E8%AC%9B%E5%BA%A7.html?rand=1523241016159

應改成
https://event05.ryzo.io/p/event05/%E6%89%8B%E6%A9%9F%E8%A1%8C%E9%8A%B7%E8%B6%A8%E5%8B%A2%E8%AC%9B%E5%BA%A7.html

即可解決你的問題

**Comment by weilyn** [comment]
hi,使用你們提供的網址進行分享還是出現錯誤的網址
有使用清快取重整的方式了

此外，因為後續的rand是系統自動加入進去的參數
我們這邊製作完成、抑或是用作分享的網址都是 https://event05.ryzo.io
並且由發布頁複製的網址都會是https://event05.ryzo.io，實在沒辦法避免rand=XXXXX的參數出現
所以可能要看一下有沒有其他更有效的解決方法
