### ISSUE TITLE
優惠序號功能儲存一直當

### ISSUE THREAD

**Issue by brendatseng** [ryuichl/fuco-report#89]
<img width="1086" alt="2018-04-10 16 41 45" src="https://user-images.githubusercontent.com/34700112/38546094-4f3bee36-3cde-11e8-8bf2-a9d1704f5ab7.png">
如圖所示，會一直卡在儲存的圈圈一直轉～無法存～～

**Comment by weilyn** [comment]
+1

**Comment by ryuichl** [comment]
你序號用幾組?

**Comment by brendatseng** [comment]
我試過1000/2000/10000

**Comment by brendatseng** [comment]
是開太多會當掉？

**Comment by ryuichl** [comment]
查了一下有發現問題
今天會找時間更新上去

**Comment by ryuichl** [comment]
已修正
請再嘗試
