### ISSUE TITLE
【建議】各區段點擊 (羅聯福/遠東Janice提供)

### ISSUE THREAD

**Issue by Grace-Tseng** [ryuichl/fuco-report#9]
可以收集到各區段的點擊

**Comment by weilyn** [comment]
客戶表示需要知道使用者的操作途徑
例如先點擊了A按鈕，接下來點擊的是B按鈕還是C按鈕...以此類推
不知道在GA的原生設定裡是否有這樣的統計數據

**Comment by ryuichl** [comment]
有這樣的數據
但暫時不會實現這個功能
這功能感覺上是給大企業用的
中小企業我想還用不到這個
