### ISSUE TITLE
EDM寄出信件中的網指直接點擊是無效的

### ISSUE THREAD

**Issue by ryzojudy** [ryuichl/fuco-report#96]
用寄發系統寄出的信
其中有一個連結是現在登入頁的網指
直接點擊連結的話 會出現【重新導向通知】的頁面
只能用複製貼上的方式 才可以進入登入頁

信件內容：
![image](https://user-images.githubusercontent.com/34263719/39284828-d6b30320-4947-11e8-8a65-a10393e5e9df.png)

重新導向通知：
![image](https://user-images.githubusercontent.com/34263719/39284835-e1b2aee2-4947-11e8-9248-60cacb520fa7.png)

**Comment by ryuichl** [comment]
你有這封信嗎
寄給我看看
感恩

**Comment by ryzojudy** [comment]
好喔~已經寄給你了~~
